spring:
  profiles:
    active: @package.environment@

mybatis:
  mapper-locations: classpath*:com/bytecamp/dao/xml/*Mapper.xml
  type-aliases-package: com.bytecamp.dao


seckill:
  product:
    # 商品缓存时间
    cache-time: 360000
  # 机器 id
  machine-id: ${SECKILL_ID:0}

  
