server:
  port: 8999

seckill:
  token:
    url: http://10.108.18.78:808/token
  reset:
    token: testresettoken
  hosts: 10.108.18.79:8080,10.108.18.80:8080

spring:
  profiles: prod
  application:
    name: seckill
  redis:
    host: 10.108.18.81
    port: 6379
    # 等待超时时间
    timeout: 1000
    pool:
      # 最大连接数
      max-total: 3000
      # 最大空闲数
      max-idle: 1000
      # 最大建立连接等待时间
      max-wait: 1000
  activemq:
    broker-url: tcp://10.108.18.78:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 1000
      idle-timeout: 10000
  jms:
    pub-sub-domain: true
  datasource:
    url: jdbc:mysql://10.108.18.77:3306/seckill?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 20
      min-idle: 20
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: true
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456